CREATE TABLE student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    surname VARCHAR(100) NOT NULL,
    nationality VARCHAR(100) NOT NULL,
    uuid VARCHAR(100) NOT NULL
);

CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    uuid CHAR(36) NOT NULL,

    FOREIGN KEY ( student_id ) REFERENCES student( id )
);

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE semester (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    part VARCHAR(10) NOT NULL
);

CREATE TABLE student_course_segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    semester_id BIGINT NOT NULL,

    FOREIGN KEY ( student_id ) REFERENCES student( id ),
    FOREIGN KEY ( course_id ) REFERENCES course( id ),
    FOREIGN KEY ( semester_id ) REFERENCES semester( id )
);


CREATE TABLE grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_course_segment_id BIGINT NOT NULL,
    grade INTEGER NOT NULL,

    FOREIGN KEY ( student_course_segment_id ) REFERENCES student_course_segment( id )
);